# Generated by Django 3.1 on 2020-10-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.CharField(default='جمعه خان', max_length=50, verbose_name='مصرف کننده'),
            preserve_default=False,
        ),
    ]
