# Generated by Django 3.1 on 2020-10-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_farebill_received'),
        ('expenses', '0003_auto_20201027_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.consignee', verbose_name='صاحب بار'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
    ]
