# Generated by Django 3.1 on 2020-11-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20201101_1618'),
        ('expenses', '0004_auto_20201027_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='consignee',
        ),
        migrations.AddField(
            model_name='item',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.billoflading', verbose_name='نمبر بارنامه'),
        ),
    ]
