# Generated by Django 3.1 on 2020-10-14 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('price', models.IntegerField(verbose_name='قیت')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('location', models.CharField(max_length=100, verbose_name='موقعیت')),
                ('status', models.CharField(choices=[('CO', 'سالم'), ('DA', 'داغمه')], max_length=2, verbose_name='حالت فعلی')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ خرید')),
            ],
        ),
    ]
