# Generated by Django 3.1 on 2020-10-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillofLading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField()),
                ('check_number', models.IntegerField()),
                ('arrival_date', models.DateField()),
                ('lading_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('origin_custom', models.CharField(max_length=50)),
                ('destination_custom', models.CharField(max_length=50)),
                ('act_cmr', models.IntegerField()),
                ('container_number', models.CharField(max_length=20)),
                ('empty_number', models.CharField(max_length=15)),
                ('commodity', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=20)),
                ('net_weight', models.IntegerField()),
                ('onatiner_weight', models.CharField(choices=[('1', 2000), ('2', 4000), ('3', 6000)], max_length=1)),
                ('licens_number', models.IntegerField()),
                ('b_l_number', models.IntegerField()),
                ('driver', models.CharField(max_length=20)),
                ('driver_father', models.CharField(max_length=20)),
                ('truck_number', models.IntegerField()),
                ('transport', models.CharField(max_length=20)),
                ('asab_shasi', models.IntegerField()),
                ('truck_shasi', models.IntegerField()),
                ('tin_jawaz', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commissionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FareBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porterage_expenses', models.IntegerField()),
                ('invoice_copy', models.IntegerField()),
                ('commission_fee', models.IntegerField()),
                ('custom_expenses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taliban_expenses', models.IntegerField()),
                ('eslam_qala_expenses', models.IntegerField()),
                ('bascol_expenses', models.IntegerField()),
                ('billoflading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.billoflading')),
            ],
        ),
        migrations.AddField(
            model_name='billoflading',
            name='commissionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.commissionaire'),
        ),
        migrations.AddField(
            model_name='billoflading',
            name='consignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.consignee'),
        ),
    ]
