# Generated by Django 3.1 on 2020-10-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billoflading',
            name='onatiner_weight',
        ),
        migrations.AddField(
            model_name='billoflading',
            name='conatiner_weight',
            field=models.CharField(choices=[('1', 2000), ('2', 4000), ('3', 6000)], default=0, max_length=1, verbose_name='وزن کانتنر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='act_cmr',
            field=models.IntegerField(verbose_name='کت )سی-ام-ار('),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='arrival_date',
            field=models.DateField(verbose_name='تاریخ ورودی'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='asab_shasi',
            field=models.IntegerField(verbose_name='شاسی اسب'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='b_l_number',
            field=models.IntegerField(verbose_name='شماره B/L'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='bill_number',
            field=models.IntegerField(verbose_name='نمبر بار نامه'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='check_number',
            field=models.IntegerField(verbose_name='نمبر بیجک'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='commissionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.commissionaire', verbose_name='کمیشنر'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='commodity',
            field=models.CharField(max_length=100, verbose_name='نوع جنس'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='consignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.consignee', verbose_name='صاحب مال'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='container_number',
            field=models.CharField(max_length=20, verbose_name='نمبر کانتینر / واکن'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='destination_custom',
            field=models.CharField(max_length=50, verbose_name='کمرک مقصد'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='driver',
            field=models.CharField(max_length=20, verbose_name='درایور'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='driver_father',
            field=models.CharField(max_length=20, verbose_name='نام پدر درایور'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='empty_number',
            field=models.CharField(max_length=15, verbose_name='کانتینر خالی'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='exit_date',
            field=models.DateField(verbose_name='تاریخ خروج'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='lading_date',
            field=models.DateField(verbose_name='تاریخ بارکیری'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='licens_number',
            field=models.IntegerField(verbose_name='شماره جواز'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='net_weight',
            field=models.IntegerField(verbose_name='وزن خالص'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='origin_custom',
            field=models.CharField(max_length=50, verbose_name='کمرک مبداء'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='quantity',
            field=models.CharField(max_length=20, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='tin_jawaz',
            field=models.IntegerField(verbose_name='تنن جواز (TIN JAWAZ)'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='transport',
            field=models.CharField(max_length=20, verbose_name='ترانسپورت'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='truck_number',
            field=models.IntegerField(verbose_name='نمبر لاری'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='truck_shasi',
            field=models.IntegerField(verbose_name='شاسی تیلر'),
        ),
    ]
