# Generated by Django 3.1 on 2020-10-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farebill',
            name='farebill_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
    ]
