# Generated by Django 3.1 on 2020-10-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201006_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='billoflading',
            name='slug',
            field=models.SlugField(default=1),
        ),
    ]
