# Generated by Django 3.1 on 2020-10-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201026_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='farebill',
            name='received',
            field=models.IntegerField(default=0, verbose_name='وصول'),
            preserve_default=False,
        ),
    ]
