# Generated by Django 3.1 on 2020-10-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_farebill_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billoflading',
            old_name='net_weight',
            new_name='total_weigth',
        ),
        migrations.RemoveField(
            model_name='billoflading',
            name='container_weight',
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='container_number',
            field=models.CharField(choices=[('CH', 'چادری'), ('KA', 'کفی'), (20, '20ft'), (40, '40ft'), (45, '45ft')], max_length=2, verbose_name='نمبر کانتینر / واکن'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='empty_number',
            field=models.CharField(choices=[(1, 'بازگشتی است'), (2, 'بازگشت شد است'), (3, 'محصولی است')], max_length=1, verbose_name='کانتینر خالی'),
        ),
    ]
