# Generated by Django 3.1 on 2020-10-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20201009_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='farebill',
            name='rent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
