# Generated by Django 3.1 on 2020-10-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20201028_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billoflading',
            name='empty_number',
            field=models.CharField(choices=[('A', 'بازگشتی است'), ('B', 'بازگشت شد است'), ('B', 'محصولی است')], max_length=1, verbose_name='کانتینر خالی'),
        ),
    ]
