# Generated by Django 3.1 on 2020-10-29 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20201029_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recive',
            name='id',
        ),
        migrations.AlterField(
            model_name='recive',
            name='bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company.billoflading'),
        ),
    ]
