# Generated by Django 3.1 on 2020-10-14 05:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20201014_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billoflading',
            name='conatiner_weight',
        ),
        migrations.AddField(
            model_name='billoflading',
            name='container_weight',
            field=models.CharField(choices=[('1', 2000), ('2', 4000), ('3', 6000)], default=0, max_length=1, verbose_name='وزن کانتنر'),
        ),
        migrations.AlterField(
            model_name='commissionaire',
            name='name',
            field=models.CharField(max_length=20, verbose_name='نام کمیشنکار'),
        ),
        migrations.AlterField(
            model_name='farebill',
            name='commission_fee',
            field=models.IntegerField(verbose_name='کمیشن بارچلانی'),
        ),
        migrations.AlterField(
            model_name='farebill',
            name='custom_expenses',
            field=models.IntegerField(verbose_name='مصارف کمرک اسلام قلعه'),
        ),
        migrations.AlterField(
            model_name='farebill',
            name='farebill_date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='farebill',
            name='invoice_copy',
            field=models.IntegerField(verbose_name='مصارف انوایس، کاپی و اتحادیه'),
        ),
        migrations.AlterField(
            model_name='farebill',
            name='porterage_expenses',
            field=models.IntegerField(verbose_name='مصارف حمالی'),
        ),
        migrations.AlterField(
            model_name='farebill',
            name='rent',
            field=models.IntegerField(verbose_name='کرایه'),
        ),
        migrations.AlterField(
            model_name='recive',
            name='bascol_expenses',
            field=models.IntegerField(verbose_name='مصارف باسکول'),
        ),
        migrations.AlterField(
            model_name='recive',
            name='eslam_qala_expenses',
            field=models.IntegerField(verbose_name='مصارف اسلام قلعه'),
        ),
        migrations.AlterField(
            model_name='recive',
            name='taliban_expenses',
            field=models.IntegerField(verbose_name='مصارف ظالمان'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieve_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ رسید')),
                ('amount', models.FloatField(verbose_name='مقدار')),
                ('consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.consignee', verbose_name='صاحب بار')),
            ],
        ),
    ]
