# Generated by Django 3.1 on 2020-10-29 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20201029_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recive',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company.billoflading'),
        ),
    ]
