# Generated by Django 3.1 on 2020-10-29 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20201029_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='recive',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recive',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.billoflading'),
        ),
    ]
