# Generated by Django 3.1 on 2020-10-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20201014_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recive',
            old_name='billoflading',
            new_name='bill',
        ),
        migrations.AddField(
            model_name='recive',
            name='i_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
