# Generated by Django 3.1 on 2020-10-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20201014_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billoflading',
            name='b_l_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره B/L'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='driver_father',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نام پدر درایور'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='lading_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ بارکیری'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='licens_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره جواز'),
        ),
    ]
