# Generated by Django 3.1 on 2020-11-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20201029_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billoflading',
            name='total_weigth',
        ),
        migrations.AddField(
            model_name='billoflading',
            name='net_weight',
            field=models.IntegerField(default=0, verbose_name='وزن خالص'),
            preserve_default=False,
        ),
    ]
