# Generated by Django 3.1 on 2020-11-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20201101_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billoflading',
            name='container_number',
            field=models.CharField(max_length=10, verbose_name='نمبر کانتینر / واکن'),
        ),
    ]
