# Generated by Django 3.1 on 2020-11-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20201101_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='billoflading',
            name='container_type',
            field=models.CharField(choices=[('CH', 'چادری'), ('KA', 'کفی'), (20, '20ft'), (40, '40ft'), (45, '45ft')], default=1, max_length=2, verbose_name='نوعیت کانتینر'),
            preserve_default=False,
        ),
    ]
