# Generated by Django 3.1 on 2020-11-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_billoflading_container_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billoflading',
            name='container_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='نمبر کانتینر / واکن'),
        ),
    ]
