# Generated by Django 3.1 on 2020-11-02 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20201101_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseBolaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amout', models.IntegerField()),
                ('reciever', models.CharField(max_length=20, null=True, verbose_name='گیرنده')),
                ('recieved_date', models.DateField(blank=True, null=True)),
                ('truck_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.driver', verbose_name='نمبر موتر')),
            ],
        ),
    ]
