# Generated by Django 3.1 on 2020-11-02 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_dosebolaq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosebolaq',
            old_name='amout',
            new_name='amount',
        ),
    ]
